inherit: 'job://looper-base'
envs:
  global:
    variables:
      SONAR_SCANNER: '${WORKSPACE}/sonar-scanner'
tools:
  nodejs: 10.14.2
  npm: 6.5.0
flows:
  default:
    - call: master-job
  pr:
    - call: pr-job
